// Base de datos de estudiantes (autogenerada por la app)
const STUDENTS = {

  // PRIMER AÑO
  "4210278": { name: "Melisa Abigail Barahona Barrera", grade: "Primer Año" },
  "4210264": { name: "Jasmín Iveth Barahona Chirino", grade: "Primer Año" },
  "19967144": { name: "Andrea Guadalupe Barrera Rivera", grade: "Primer Año" },
  "20068438": { name: "Keiry Nineth Bonilla Díaz", grade: "Primer Año" },
  "19959332": { name: "Érika Maricela Chávez Castellanos", grade: "Primer Año" },
  "4210262": { name: "María Luz Córdova Garmendia", grade: "Primer Año" },
  "20062373": { name: "Rosa Andrea Cruz Serrano", grade: "Primer Año" },
  "19843597": { name: "Bryan Miguel Flores López", grade: "Primer Año" },
  "4210272": { name: "David Ernesto Fuentes Meléndez", grade: "Primer Año" },
  "19967158": { name: "Liliana del Carmen Hernández Alfaro", grade: "Primer Año" },
  "4210284": { name: "Yeferson Alexis Maravilla Esquivel", grade: "Primer Año" },
  "19934099": { name: "Bryan Wilfredo Martínez Chirino", grade: "Primer Año" },
  "19967161": { name: "Rocío Azucena Mejía Arévalo", grade: "Primer Año" },
  "19967151": { name: "Yaquelin Marisol Montano Fuentes", grade: "Primer Año" },
  "20062496": { name: "Katherinne Yesenia Palma Merino", grade: "Primer Año" },
  "19788973": { name: "Alexandra Elizabeth Portillo Martínez", grade: "Primer Año" },
  "3167629": { name: "Keren Lorena Portillo Martínez", grade: "Primer Año" },
  "19967163": { name: "María José Quezada Alfaro", grade: "Primer Año" },
  "4210259": { name: "Kennedy Alexander Ramírez Meléndez", grade: "Primer Año" },
  "4210276": { name: "María Fernanda Rivas Barahona", grade: "Primer Año" },
  "20062499": { name: "Wilian Alexander Rivera Montano", grade: "Primer Año" },
  "6954866": { name: "Érika Berenice Rodríguez Majano", grade: "Primer Año" },
  "4210263": { name: "David Isaías Romero López", grade: "Primer Año" },

  // SEGUNDO AÑO
  "4210279": { name: "José María Barrera Barahona", grade: "Segundo Año" },
  "4210254": { name: "Amílcar Abel Barrera Hernández", grade: "Segundo Año" },
  "2724749": { name: "Maicol Antuan Barrera Rodríguez", grade: "Segundo Año" },
  "6473557": { name: "Estephany Azucena Berríos Mejía", grade: "Segundo Año" },
  "6473562": { name: "Amy Daniela Cañas Chávez", grade: "Segundo Año" },
  "19724473": { name: "Mauricio Edgardo Córdova Ascencio", grade: "Segundo Año" },
  "6473555": { name: "Óscar Kennedy Cornejo Santana", grade: "Segundo Año" },
  "4210255": { name: "Carlos Estiven Hernández Chávez", grade: "Segundo Año" },
  "1964480": { name: "Juan David Hernández Martínez", grade: "Segundo Año" },
  "4210256": { name: "Yuleyde Guadalupe López Ramos", grade: "Segundo Año" },
  "5531752": { name: "Cintia Yamileth Martínez Barrera", grade: "Segundo Año" },
  "4210268": { name: "Wilmer Bladimir Mejía Angulo", grade: "Segundo Año" },
  "2295119": { name: "Fátima Lisbeth Mejía Guzmán", grade: "Segundo Año" },
  "5531765": { name: "Kevin Gabriel Monterrosa Méndez", grade: "Segundo Año" },
  "2294851": { name: "Alfredo José Osorio Reina", grade: "Segundo Año" },
  "19769235": { name: "Ángel Moisés Quezada Alfaro", grade: "Segundo Año" },
  "19929938": { name: "Elizabeth Sophia Quinteros Miranda", grade: "Segundo Año" },
  "4210277": { name: "Josué Leonel Rivera Montano", grade: "Segundo Año" },

  // SÉPTIMO
  "20176653": { name: "Karen Daniela Aguilero Bonilla", grade: "Séptimo" },
  "20176654": { name: "Anderson Moisés Alfaro Barahona", grade: "Séptimo" },
  "20176658": { name: "Tania Elizabeth Barrera Rivera", grade: "Séptimo" },
  "20316947": { name: "Lesly Gisselle Bonilla Díaz", grade: "Séptimo" },
  "20176659": { name: "Ernesto Adonay Castillo Chirino", grade: "Séptimo" },
  "20182709": { name: "Rosa Esperanza Chirino Alfaro", grade: "Séptimo" },
  "20176660": { name: "Reyna Guadalupe Chirino Corvera", grade: "Séptimo" },
  "20316949": { name: "Edwar Bladimir Córdova Martínez", grade: "Séptimo" },
  "20298183": { name: "Andrea Elizabeth Corvera Anzora", grade: "Séptimo" },
  "20062372": { name: "Lesly Paola Cruz Serrano", grade: "Séptimo" },
  "20298185": { name: "Víctor José Flores Varela", grade: "Séptimo" },
  "20199089": { name: "Alessandro Ariel Fuentes Ramos", grade: "Séptimo" },
  "20182722": { name: "Daniela Alejandra Henríquez Córdova", grade: "Séptimo" },
  "20141583": { name: "Geovanny Alejandro Jiménez Henríquez", grade: "Séptimo" },
  "20138865": { name: "Manuel Alejandro Jiménez Henríquez", grade: "Séptimo" },
  "20298188": { name: "Génesis Johana Maldonado Hernández", grade: "Séptimo" },
  "20062488": { name: "Fredis Antonio Maravilla Esquivel", grade: "Séptimo" },
  "20182730": { name: "Cristofer Daniel Martínez Chirino", grade: "Séptimo" },
  "20062492": { name: "Marlon Edgardo Mena Corvera", grade: "Séptimo" },
  "20298191": { name: "Luis Enrique Paredes Chirino", grade: "Séptimo" },
  "10000395": { name: "Nathaly Valeria Portillo Cruz", grade: "Séptimo" },
  "20298192": { name: "Naomi de los Ángeles Ramírez Ramos", grade: "Séptimo" },
  "20298195": { name: "Karla Guadalupe Ríos Hernández", grade: "Séptimo" },
  "20298194": { name: "Lidia Marcela Rivas Barahona", grade: "Séptimo" },
  "20176670": { name: "Azariel de Jesús Rivas Barrera", grade: "Séptimo" },
  "20316951": { name: "Axel Dagoberto Romero Barrera", grade: "Séptimo" },
  "20171117": { name: "Isabel Arlette Sánchez Castellón", grade: "Séptimo" },
  "20298196": { name: "María Magdalena Servellón Barrera", grade: "Séptimo" },

  // PRUEBAS
  "1999": { name: "José Eliseo Martínez", grade: "Maestro" },
};
