// Base de datos de estudiantes (autogenerada por la app)
const STUDENTS = {

  // NOVENO
  "20062471": { name: "Diego Antonio Aguilero Bonilla", grade: "Noveno" },
  "19967142": { name: "Darwin Estiven Alfaro Barahona", grade: "Noveno" },
  "19971566": { name: "Dayana Yamileth Angulo Ayala", grade: "Noveno" },
  "19971565": { name: "Yesenia Esmeralda Angulo Ayala", grade: "Noveno" },
  "19967143": { name: "Marlon Alberto Barrera Arévalo", grade: "Noveno" },
  "20062474": { name: "César David Barrera Canjura", grade: "Noveno" },
  "19967145": { name: "Óscar Alexis Campos Fuentes", grade: "Noveno" },
  "19967146": { name: "Elizabeth del Carmen Cañas Paredes", grade: "Noveno" },
  "19934096": { name: "Gisela Elizabeth Córdova Ascencio", grade: "Noveno" },
  "19934095": { name: "Ingrid Valeria Córdova Chirino", grade: "Noveno" },
  "4210274": { name: "Pedro Alexis Escamilla Vásquez", grade: "Noveno" },
  "20200673": { name: "Karla Michel Escobar Aguilar", grade: "Noveno" },
  "20062484": { name: "Wendy Arely García Canjura", grade: "Noveno" },
  "19934098": { name: "Adonay Antonio Hernández Meléndez", grade: "Noveno" },
  "19967150": { name: "Anggie Guadalupe López Cornejo", grade: "Noveno" },
  "20062486": { name: "Rosa Emilia Maldonado Baires", grade: "Noveno" },
  "20062489": { name: "José Ernesto Martínez Maldonado", grade: "Noveno" },
  "19976021": { name: "Angelita Damary Martínez Portillo", grade: "Noveno" },
  "20023247": { name: "Alexandra Elizabeth Monterroza Muñoz", grade: "Noveno" },
  "19976024": { name: "Claritza Anahy Muñoz Corvera", grade: "Noveno" },
  "20062495": { name: "Carolina Esmeralda Osorio Guzmán", grade: "Noveno" },
  "19956103": { name: "Griseida Jasmín Pérez López", grade: "Noveno" },
  "20062498": { name: "Silvia Yamileth Ramos Peña", grade: "Noveno" },
  "19967154": { name: "César Daniel Rivas Barahona", grade: "Noveno" },

  // PRIMER AÑO
  "4210278": { name: "Melisa Abigail Barahona Barrera", grade: "Primer Año" },
  "4210264": { name: "Jasmín Iveth Barahona Chirino", grade: "Primer Año" },
  "19967144": { name: "Andrea Guadalupe Barrera Rivera", grade: "Primer Año" },
  "20068438": { name: "Keiry Nineth Bonilla Díaz", grade: "Primer Año" },
  "19959332": { name: "Érika Maricela Chávez Castellanos", grade: "Primer Año" },
  "4210262": { name: "María Luz Córdova Garmendia", grade: "Primer Año" },
  "20062373": { name: "Rosa Andrea Cruz Serrano", grade: "Primer Año" },
  "19843597": { name: "Bryan Miguel Flores López", grade: "Primer Año" },
  "4210272": { name: "David Ernesto Fuentes Meléndez", grade: "Primer Año" },
  "19967158": { name: "Liliana del Carmen Hernández Alfaro", grade: "Primer Año" },
  "4210284": { name: "Yeferson Alexis Maravilla Esquivel", grade: "Primer Año" },
  "19934099": { name: "Bryan Wilfredo Martínez Chirino", grade: "Primer Año" },
  "19967161": { name: "Rocío Azucena Mejía Arévalo", grade: "Primer Año" },
  "19967151": { name: "Yaquelin Marisol Montano Fuentes", grade: "Primer Año" },
  "20062496": { name: "Katherinne Yesenia Palma Merino", grade: "Primer Año" },
  "19788973": { name: "Alexandra Elizabeth Portillo Martínez", grade: "Primer Año" },
  "3167629": { name: "Keren Lorena Portillo Martínez", grade: "Primer Año" },
  "19967163": { name: "María José Quezada Alfaro", grade: "Primer Año" },
  "4210259": { name: "Kennedy Alexander Ramírez Meléndez", grade: "Primer Año" },
  "4210276": { name: "María Fernanda Rivas Barahona", grade: "Primer Año" },
  "20062499": { name: "Wilian Alexander Rivera Montano", grade: "Primer Año" },
  "6954866": { name: "Érika Berenice Rodríguez Majano", grade: "Primer Año" },
  "4210263": { name: "David Isaías Romero López", grade: "Primer Año" },

  // PRUEBAS
  "1999": { name: "José Eliseo Martínez", grade: "Maestro" },
};
